backend:
  name: github
  repo: Artificial-Ryan/Artificial-Ryan.github.io
  branch: main
  base_url: https://github.com
  auth_type: implicit
  app_id: Ov23lif8gYDI3vQ0D2w4 # Your GitHub OAuth Client ID

media_folder: "img/uploads" # Folder where uploaded media will be stored
public_folder: "/img/uploads" # The public path to the media folder

collections:
  - name: "blog" # A friendly name for the collection
    label: "Blog Posts" # The name of the collection in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template for new posts
    fields: # The fields for each document, these are the fields you'll see in the UI
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}